# Generated by Django 6.0.4 on 2026-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField()),
                ('room_type', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PU', max_length=3)),
                ('password', models.CharField(default=None, max_length=128, null=True)),
            ],
        ),
    ]
