# Generated by Django 6.0.4 on 2026-04-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
