# Generated by Django 6.0.4 on 2026-04-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_chatroom_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='channel_owner',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
