# Generated by Django 6.0.4 on 2026-04-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_chatroom_channel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='channel_owner',
        ),
    ]
