# Generated by Django 6.0.4 on 2026-04-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_chatroom_channel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='num_connections',
            field=models.IntegerField(default=0),
        ),
    ]
